name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-browser

      - name: Run Robot Framework Tests
        run: |
          robot programmierprojekt/Test.robot
