name: Run Robot Framework Tests and Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  test_and_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Robot Framework and Browser library
        run: |
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results programmierprojekt/Test.robot

      - name: Generate Report and Log
        run: |
          rebot --outputdir results results/output.xml

      - name: Publish Documentation
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: results/
