name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ändere die Version, wenn nötig

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Wähle die passende Node.js Version

      - name: Install Robot Framework and Browser library
        run: |
          pip install robotframework
          pip install robotframework-browser

      - name: Install Browser library dependencies
        run: |
          python -m browser install

      - name: Run Robot Framework Tests
        run: |
          robot programmierprojekt/Test.robot
